### ISSUE TITLE
It doesnt work 

### ISSUE THREAD

**Issue by FernandoPrzGmz** [HafidOD/divisorSilabico.cpp#1]
@HafidOD  

- :angry:
- :angry: 
- :angry:
- :angry: 
- :angry:
- :angry:

**Comment by HafidOD** [comment]
Descarga el codigo, compilas con los comandos: g++ ./divisor silábico.cpp -lwinmm

**Comment by FernandoPrzGmz** [comment]
I have a problem with **windows.h** package.

**Comment by HafidOD** [comment]
I leave the code and .exe: https://drive.google.com/folderview?id=11Dgyf8u3IUoqGfWrQJVZrGHnoRHYo0rG
